baseURL = "/"
languageCode = "cs-cz"
defaultContentLanguage = "cs-cz"
title = "Lukáš Matuška"
theme = "hallo"
disableKinds = ["taxonomy", "taxonomyTerm"]
[Author]
    name = "Backend developer"
# summaryLength = 30
[params]
    siteURL = "https://lukasmatuska.cz"
    lang = "cs"
    locale = "cs_CZ"
    # gatag = ""
    greeting = "Lukáš Matuška"
    [[params.links]]
        icon = "gitlab"
        title = "GitLab"
        url = "https://gitlab.com/matuska.lukas/"
    [[params.links]]
        icon = "github"
        title = "GitHub"
        url = "https://github.com/lukynmatuska/"
    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:matuska.lukas@lukasmatuska.cz"
    [[params.links]]
        icon = "youtube"
        title = "YouTube"
        url = "https://www.youtube.com/channel/UCUaaFvEgEyPT-oEoZpHJL4A"
    [[params.links]]
        icon = "twitter"
        title = "Twitter"
        url = "https://twitter.com/lukynmatuska"
    [[params.links]]
        icon = "instagram"
        title = "Instagram"
        url = "https://instagram.com/lukynmatuska"