baseURL = "/"
defaultContentLanguage = "cs"
defaultContentLanguageInSubdir = true
title = "Lukáš Matuška"
disableKinds = ["taxonomy", "taxonomyTerm"]
[languages]
  [languages.cs]
    weight = 0
    languageName = "Čeština"
    [languages.cs.menu]
        [[languages.cs.menu.main]]
            url    = "/cs/"
            name   = "Domů"
            weight = 1
        [[languages.cs.menu.main]]
            url    = "/cs/projects"
            name   = "Projekty"
            weight = 2
        # [[languages.cs.menu.main]]
            # url    = "/cs/contact/"
            # name   = "Kontakt"
            # weight = 3
        # [[languages.cs.menu.main]]
            # url    = "/cs/blog/"
            # name   = "Blog"
            # weight = 4
  [languages.en]
    weight = 1
    languageName = "English"
    [languages.en.menu]
        [[languages.en.menu.main]]
            url    = "/en/"
            name   = "Home"
            weight = 1
        [[languages.en.menu.main]]
            url    = "/en/projects"
            name   = "Projects"
            weight = 2
        # [[languages.en.menu.main]]
            # url    = "/en/contact/"
            # name   = "Contact"
            # weight = 3
        # [[languages.en.menu.main]]
            # url    = "/en/blog/"
            # name   = "Blog"
            # weight = 4
[params]
    [[params.links]]
        icon = "gitlab"
        title = "GitLab"
        url = "https://gitlab.com/matuska.lukas/"
    [[params.links]]
        icon = "github"
        title = "GitHub"
        url = "https://github.com/lukynmatuska/"
    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:matuska.lukas@lukasmatuska.cz"
    [[params.links]]
        icon = "youtube"
        title = "YouTube"
        url = "https://www.youtube.com/channel/UCUaaFvEgEyPT-oEoZpHJL4A"
    [[params.links]]
        icon = "twitter"
        title = "Twitter"
        url = "https://twitter.com/lukynmatuska"
    [[params.links]]
        icon = "instagram"
        title = "Instagram"
        url = "https://instagram.com/lukynmatuska"
    [[params.links]]
        icon = "facebook"
        title = "Facebook"
        url = "https://www.facebook.com/lukyn.matuska"
    [[params.links]]
        icon = "phone"
        title = "Phone"
        iconset = "fas"
        url = "tel:604192783"