baseURL = "/"
defaultContentLanguage = "cs"
defaultContentLanguageInSubdir = true
title = "Lukáš Matuška"
theme = "hallo"
disableKinds = ["taxonomy", "taxonomyTerm"]
[languages]
  [languages.cs]
    weight = 0
    languageName = "Čeština"
    [languages.cs.menu]
        [[languages.cs.menu.main]]
            url    = "/cs/projects"
            name   = "Projekty"
        [[languages.cs.menu.main]]
            url    = "/cs/"
            name   = "Domů"
        # [[languages.cs.menu.main]]
        #     url    = "/en/contact/"
        #     name   = "Kontakt"
        # [[languages.cs.menu.main]]
        #     url    = "/cs/blog/"
        #     name   = "Blog"
    [languages.cs.Author]
        name = "Lukáš Matuška"
        description = "Backend developer"
  [languages.en]
    weight = 1
    languageName = "English"
    [languages.en.menu]
        [[languages.en.menu.main]]
            url    = "/en/projects"
            name   = "Projects"
        [[languages.en.menu.main]]
            url    = "/en/"
            name   = "Home"
        # [[languages.en.menu.main]]
        #     url    = "/en/contact/"
        #     name   = "Contact"
        # [[languages.en.menu.main]]
        #     url    = "/en/blog/"
        #     name   = "Blog"
    [languages.en.Author]
        name = "Lukas Matuska"
        description = "Backend developer"
# summaryLength = 30
[params]
    description = "My personal website"
    siteURL = "https://lukasmatuska.cz"
    lang = "cs"
    locale = "cs_CZ"
    # gatag = ""
    greeting = "Lukáš Matuška"
    [[params.links]]
        icon = "gitlab"
        title = "GitLab"
        url = "https://gitlab.com/matuska.lukas/"
    [[params.links]]
        icon = "github"
        title = "GitHub"
        url = "https://github.com/lukynmatuska/"
    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:matuska.lukas@lukasmatuska.cz"
    [[params.links]]
        icon = "youtube"
        title = "YouTube"
        url = "https://www.youtube.com/channel/UCUaaFvEgEyPT-oEoZpHJL4A"
    [[params.links]]
        icon = "twitter"
        title = "Twitter"
        url = "https://twitter.com/lukynmatuska"
    [[params.links]]
        icon = "instagram"
        title = "Instagram"
        url = "https://instagram.com/lukynmatuska"