baseURL = "https://lukasmatuska.cz"
defaultContentLanguage = "cs"
defaultContentLanguageInSubdir = true
title = "Lukáš Matuška"
disableKinds = ["taxonomy", "taxonomyTerm"]
[languages]
  [languages.cs]
    weight = 1
    languageName = "Čeština"
    [languages.cs.params]
        locale = "cs_CZ"
   [languages.en]
    weight = 2
    languageName = "English"
    [languages.en.params]
        locale = "en_US"
[params]
    siteURL = "https://lukasmatuska.cz"
    lang = "cs"
    locale = "cs_CZ"
    gatag = "293469174"
    [taxonomies]
        series = "series"
    [[params.links]]
        icon = "gitlab"
        title = "GitLab"
        url = "https://gitlab.com/matuska.lukas/"
    [[params.links]]
        icon = "github"
        title = "GitHub"
        url = "https://github.com/lukynmatuska/"
    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:matuska.lukas@lukasmatuska.cz"
    [[params.links]]
        icon = "youtube"
        title = "YouTube"
        url = "https://www.youtube.com/channel/UCUaaFvEgEyPT-oEoZpHJL4A"
    [[params.links]]
        iconset = "fab"
        icon = "spotify"
        title = "Spotify"
        url = "https://open.spotify.com/user/11126634413"
    [[params.links]]
        icon = "twitter"
        title = "Twitter"
        url = "https://twitter.com/lukasmatuskacz"
    [[params.links]]
        icon = "instagram"
        title = "Instagram"
        url = "https://instagram.com/lukynmatuska"
    [[params.links]]
        icon = "facebook"
        title = "Facebook"
        url = "https://www.facebook.com/lukyn.matuska"
    [[params.links]]
        icon = "steam"
        title = "Steam"
        url = "https://steamcommunity.com/profiles/76561198126079003"
    [[params.links]]
        iconset = "fas"
        icon = "graduation-cap"
        title = "VUT"
        url = "https://www.vut.cz/lide/lukas-matuska-242174"
    [[params.links]]
        icon = "discord"
        title = "Discord"
        url = "./discord"
    [[params.links]]
        icon = "phone"
        title = "Phone"
        iconset = "fas"
        url = "tel:604192783"
[params.seo]
    image = "/images/portrait.webp"
