[[redirects]]
	from = "/en/*"
	to = "/en/404/"
	status = 404

[[redirects]]
	from = "/cs/*"
	to = "/cs/404/"
	status = 404

[[redirects]]
	from = "/cw"
	to = "https://forms.gle/mJKe6p8bceVGXyge8"
	status = 301

[[redirects]]
	from = "/cwc"
	to = "https://drive.google.com/file/d/11hEI5bAhj3WRY3Z1qUsUQPdmMs8vhp4_/view"
	status = 301

[[redirects]]
	from = "/cwzv"
	to = "https://forms.gle/U5g8GtZy9CbNzZK48"
	status = 301

[[redirects]]
	from = "/cardas"
	to = "https://forms.gle/mJKe6p8bceVGXyge8"
	status = 301

[[redirects]]
	from = "/cms"
	to = "https://drive.google.com/drive/folders/1fJH6JeCJOgAXXptIpNhKSd1XeBnWogId"
	status = 301

[[redirects]]
	from = "/*"
	to = "/en/404/"
	status = 404

[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.split1]
  command = "hugo --gc --minify --enableGitInfo"

  [context.split1.environment]
	HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"
